version: '3.9'

services:
  discovery_service:
    container_name: discover_service
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - PORT=8761
    depends_on:
      - postgresql
    env_file:
      - .env


  profile_service:
    container_name: profile_service
    build: 
      context: profile_service
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment:
      - PORT=8000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    depends_on:
      - postgresql
      - discovery_service
    env_file:
      - .env


  postgresql:
    image: postgres:15
    container_name: luvr_postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: