import os

POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE = os.getenv("EUREKA_CLIENT_SERVICEURL_DEFAULTZONE")