version: '3.9'

services:
  backend:
    container_name: luvr_backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/backend/app/
    environment:
      - PORT=8000
    depends_on:
      - postgresql
    env_file:
      - .env

  postgresql:
    image: postgres:15
    container_name: luvr_postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: