spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/docs
          filters:
            - RewritePath=/user-service/docs, /docs

server:
  port: 8080

eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}