spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/luvr-app
          jwk-set-uri: http://localhost:8080/realms/luvr-app/protocol/openid-connect/certs


server:
  port: 8765

eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
