spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**

server:
  port: 8765

eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt:
   secret: ${JWT_SECRET}